# Settings that the LAMMPS build will import when this package library is used

# settings for MLIP on UBUNTU18.04

polymlp_INC = -fopenmp -std=c++11 -DLAMMPS_EXCEPTIONS
polymlp_PATH = -L../../lib/polymlp

# include boost 
polymlp_SYSINC = -I/home/seko/usr/include
polymlp_SYSLIB = -L/home/seko/usr/lib -lgomp

