# Settings that the LAMMPS build will import when this package library is used

polymlp_INC = -fopenmp -std=c++11 -DLAMMPS_EXCEPTIONS
polymlp_PATH = -L../../lib/polymlp

polymlp_SYSINC = 
polymlp_SYSLIB = -lgomp

